name: Get Zenodo concept ID
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  variables: write
  contents: read

jobs:  
  get-concept-id:  
    if: >-
      ${{ !github.event.repository.is_template }}

    runs-on: ubuntu-latest
    name: Get Zenodo concept ID
    steps:
      - name: Get Zenodo concept ID
        id: get_concept_id
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Check if the ZENODO_CONCEPT_ID variable is set
          if [ -z "${{ vars.ZENODO_CONCEPT_ID }}" ]; then
              # Create a new deposition and get the Concept ID
              echo "Creating deposition..."
              RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions" \
                -H "Content-Type: application/json" \
                -H "Authorization: Bearer ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}" \
                -d '{}')

              echo "Zenodo API Response: $RESPONSE"
              
              DEPOSITION_ID=$(echo "$RESPONSE" | jq -r '.id // empty')
              CONCEPT_ID=$(echo "$RESPONSE" | jq -r '.conceptrecid // empty')

              echo "Deposition ID: $DEPOSITION_ID"
              echo "Concept ID: $CONCEPT_ID"

              if [ -z "$CONCEPT_ID" ]; then
                  echo "Error: Failed to get Concept ID from Zenodo response"
                  exit 1
              fi

              # Set the Concept ID as a repository variable
              gh api --method POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "/repos/${{ github.repository }}/actions/variables" \
                -f "name=ZENODO_CONCEPT_ID" \
                -f "value=$CONCEPT_ID" || {
                  echo "Error: Failed to set ZENODO_CONCEPT_ID variable"
                  exit 1
                }
          else
              echo "ZENODO_CONCEPT_ID=${{ vars.ZENODO_CONCEPT_ID }}"
          fi