name: Publish to Zenodo
on:
  # Trigger when you publish a release via GitHub's release page
  release:
    types:
      - published
  workflow_dispatch:


jobs:
  publish-fig:
      runs-on: ubuntu-latest
      name: Publish figure to Zenodo
      steps:
        - uses: ipcc-ar7/publish-zenodo@v1.0.2
          with:
            files: |
              *.png
              README.md
              CITATION.cff
              LICENSE
              fig.*

            github_token: ${{ secrets.GITHUB_TOKEN }}
            zenodo_token: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
            sandbox: true
            publish: false
            concept: ''
            upsert_doi: false
            upsert_location: doi
            verbose: true

  publish-data:
      runs-on: ubuntu-latest
      name: Publish data to Zenodo
      defaults:
        run:
          working-directory: data
      steps:
        - uses: ipcc-ar7/publish-zenodo@v1.0.2
          with:
            files: |
              *
            github_token: ${{ secrets.GITHUB_TOKEN }}
            zenodo_token: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
            sandbox: true
            publish: false
            concept: ''
            upsert_doi: false
            upsert_location: doi
            verbose: true

