name: Publish to Zenodo
on:
  # Trigger when you publish a release via GitHub's release page
  release:
    types:
      - published
  workflow_dispatch:


jobs:
  publish:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the contents of your repository
          uses: actions/checkout@v4

        - name: Create a draft snapshot of your repository figure content.
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          uses: zenodraft/action@0.13.3
          with:
            concept: 123832
            filenames: "*.png README.md CITATION.cff LICENSE fig.*"
            publish: false
            sandbox: true
            # upsert-doi: true
            # upsert-location:
            verbose: true
