name: Publish to Zenodo
on:
  # Trigger when you publish a release via GitHub's release page or manually via the Actions tab
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish-fig:
      runs-on: ubuntu-latest
      name: Publish figure to Zenodo
      steps:
        - name: Checkout the contents of your repository
          uses: actions/checkout@v4

        - uses: ipcc-ar7/publish-zenodo@v1.10
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          with:
            # Note that Zenodo only accepts root level files.
            files: |
              *.png
              README.md
            metadata: figure.yml
            sandbox: true
            publish: true
            concept: ${{ vars.ZENODO_CONCEPT_ID }}
            verbose: true


 publish-data:
     runs-on: ubuntu-latest
     name: Publish data to Zenodo
     steps:
       - name: Checkout the contents of your repository' data folder
         uses: actions/checkout@v4

       - uses: ipcc-ar7/publish-zenodo@v1.10
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
         with:
           files: |
             data/*
           metadata: data/data.yml
           sandbox: true
           publish: false
           concept: ''
           verbose: true

