name: Publish to Zenodo
on:
  # Trigger when you publish a release via GitHub's release page
  release:
    types:
      - published
  workflow_dispatch:


jobs:
  publish-fig:
      runs-on: ubuntu-latest
      name: Publish figure to Zenodo
      steps:
        - name: Checkout the contents of your repository
          uses: actions/checkout@v4

        - uses: ipcc-ar7/publish-zenodo@v1.7
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          with:
            files: |
              figure/*
              README.md
            sandbox: true
            publish: false
            concept: ''
            verbose: true

#  publish-data:
#      runs-on: ubuntu-latest
#      name: Publish data to Zenodo
#      steps:
#        - name: Checkout the contents of your repository' data folder
#          uses: actions/checkout@v4
#
#        - name: Zip data
#          run: (cd data; zip -r ../data.zip *)
#
#        - uses: ipcc-ar7/publish-zenodo@v1.4
#          env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
#          with:
#            files: |
#              data.zip
#            citation: data/CITATION.cff
#            sandbox: true
#            publish: false
#            concept: ''
#            verbose: true

