name: json-yaml-validate
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # enable write permissions for pull request comments

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check mandatory files are present
        id: check_files
        uses: thebinaryfelix/check-file-existence-action@v1
        with:
          files: 'LICENSE, README.md, info.yml, .schema/info.json, data/README.md, *.png'

      - name: Validate YAML using JSON schema
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v3.2.1
        with:
          comment: "true" # enable comment mode
          files:
            - info.yml
          yaml_as_json: "true"
          json_schema: .schema/info.json


