name: json-yaml-validate
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # enable write permissions for pull request comments

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run regexp on repo name to extract draft order
        id: regex-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.repository.name }}
          regex: '^ar7-(\w+)-(\w+)-(\w+)-(\w+)$'

      - name: Echo regexp match
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: echo "Draft order -> ${{ steps.regex-match.outputs.group2 }}"

      - name: Fail if no match
        if: ${{ steps.regex-match.outputs.match == '' }}
        run: echo "Repository name does not match template"; exit 1

      - name: Check file existence
        uses: andstor/file-existence-action@v3
        with:
          files: "LICENSE, README.md, CITATION.cff, data/README.md, *.png"
          fail: "true"

# Slow
#      - name: Validate CITATION.cff
#        uses: dieghernan/cff-validator@v3

#      - name: Check whether the citation metadata from CITATION.cff is valid
#        uses: citation-file-format/cffconvert-github-action@2.0.0
#        with:
#          args: "--validate"

      - name: Copy CITATION.cff to CITATION.yml
        run: cp CITATION.cff CITATION.yml

      - name: Validate CITATION.yml
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v3.2.1
        with:
          comment: "true" # enable comment mode
          files: |
            CITATION.yml
          yaml_as_json: "true"
          json_schema: .schema/citation.json

      - name: Check minimum requirements according to draft version
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v3.2.1
        with:
          comment: "true" # enable comment mode
          files: |
            CITATION.yml
          yaml_as_json: "true"
          json_schema: .schema/${{ steps.regex-match.outputs.group2 }}.json


