name: json-yaml-validate
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # enable write permissions for pull request comments

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Run regexp on repo name to extract draft order"
        id: regex-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.repository.name }}
          regex: '^ar7-(\w+)-(\w+)-(\w+)-(\w+)$'

      - name: "Echo regexp match"
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: echo "Draft order is ${{ steps.regex-match.outputs.group2 }}"

      - name: "Check file existence"
        uses: andstor/file-existence-action@v3
        with:
          files: "LICENSE, README.md, info.yml, data/README.md, *.png"
          fail: "true"

      - name: Validate YAML using JSON schema
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v3.2.1
        with:
          comment: "true" # enable comment mode
          files: |
            info.yml
          yaml_as_json: "true"
          json_schema: .schema/${{ steps.regex-match.outputs.group2 }}.json


