name: Schema validation
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # enable write permissions for pull request comments

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run regexp on repo name to extract draft order
        id: regex-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.repository.name }}
          regex: '^ar7-(\w+)-(\w+)-(\w+)-(\w+)$'

      - name: Create JSON file with repo name components (report, draft, chapter, figure)
        run: echo "{\"report\":\"${{ steps.regex-match.outputs.group1 }}\",\"draft\":\"${{ steps.regex-match.outputs.group2 }}\",\"chapter\":\"${{ steps.regex-match.outputs.group3 }}\",\"figure\":\"${{ steps.regex-match.outputs.group4 }}\"}" > repo_name.json

      - name: Check repo name components against schema
        id: validate-repo-name
        uses: GrantBirki/json-yaml-validate@v3.2.1
        with:
          comment: "true" # enable comment mode
          files: |
            repo_name.json
          json_schema: .schema/repo_name.json

      - name: Check figure.yml against Zenodo schema
        id: validate-figure
        uses: GrantBirki/json-yaml-validate@v3.2.1
        with:
          comment: "true" # enable comment mode
          files: |
            figure/figure.yml
          yaml_as_json: "true"
          json_schema: .schema/zenodo_v0.3.0.json
          avj_strict_mode: "false"

      - name: Check file existence
        uses: andstor/file-existence-action@v3
        with:
          files: "LICENSE, README.md, CITATION.cff, data/README.md, *.png"
          fail: "true"





